### ISSUE TITLE
您好 可否写一个这样风格的主题

### ISSUE THREAD

**Issue by liuxudan** [icylogic/carbon#1]
wordpress typecho 的原文件都有，可否写一个这样的主题 谢谢
http://chopstack.com/

**Comment by icylogic** [comment]
@liuxudan 我觉得需要征求原作者同意吧 ... 或者作者在哪里有 theme 的 license

**Comment by liuxudan** [comment]
我和作者联系过，作者没有反对。 
wordpress     theme     https://github.com/iMuFeng/maupassant
typecho         theme    https://github.com/pagecho/maupassant/
farbox            theme    https://github.com/pagecho/Maupassant-farbox
Octopress     theme    https://github.com/pagecho/mewpassant
作者不用HEXO 所以就没有出HEXO THEME

**Comment by liuxudan** [comment]
她这款主题 符和您 简约 在各种设备上 通吃。

**Comment by icylogic** [comment]
@liuxudan OK, 我找时间 fork 一份, 弄好了通知你

**Comment by liuxudan** [comment]
谢谢 您的QQ号多少？ 希望成为你的网络朋友。

**Comment by icylogic** [comment]
嗯 ... 可以发邮件到 withguohao # gmail.com 吗, 不太想直接公开 QQ

**Comment by liuxudan** [comment]
好啊。

**Comment by icylogic** [comment]
@liuxudan [maupassant-hexo](https://github.com/icylogic/maupassant-hexo) 简单转换了一下, 你先试试

**Comment by liuxudan** [comment]
收到
