### ISSUE TITLE
Add gh-pages for a demo

### ISSUE THREAD

**Issue by icylogic** [icylogic/carbon#11]

**Comment by thinkingofmaud** [comment]
No experience with github-pages, but maybe I can do it.
Made a quick look at other themes pages.
Do you suggest something other than [this](https://github.com/hexojs/hexo-theme-light/tree/site/source/_posts) for demo posts?

**Comment by icylogic** [comment]
I mean this [User, Organization, and Project Pages](https://help.github.com/articles/user-organization-and-project-pages/).
With a gh-pages branch which contains static files, we could make a demo site like icylogic.github.io/carbon.

**Comment by icylogic** [comment]
[Theme Test](http://icylogic.github.io/carbon/)

Maybe I should make a multi-language version in the future

**Comment by icylogic** [comment]
[Theme Test](http://icylogic.github.io/carbon/)
Maybe I should make a multi-language version in the future.

**Comment by thinkingofmaud** [comment]
The demo does not show support for comments. Maybe a post showing duoshuo and another showing disqus support.

I dont know if its an issue, but mathjax enabled text/formulas get bolder 5 seconds after loading.
Is that right?
I experienced this on chrome, firefox and waterfox on win64.

**Comment by icylogic** [comment]
Showing multiple comments is a good idea. I will make it in next commits.
I've also experienced this. It seems to be performed by js from mathjax. I should read more docs.
