### ISSUE TITLE
关于是怎么设置的

### ISSUE THREAD

**Issue by yuelng** [icylogic/carbon#19]
请问“关于”在这个主题中是怎么设置的呢？怎么连接

**Comment by icylogic** [comment]
https://github.com/icylogic/carbon/blob/master/_config.yml#L2
也就是 $hexo_dir/themes/carbon/_config.yml

**Comment by yuelng** [comment]
我知道这里是about，主要是我不清楚，怎么连接到文章

**Comment by yuelng** [comment]
嗯嗯，查到怎么办了，首先在主目录找到_config.yml，找到url添加about_dir: about到这个板块。然后在/source里面建立about文件夹。在about文件夹里建立index.md。编辑index.md就和发布其他的文章一样，格式都一样。

**Comment by icylogic** [comment]
嗯，有什么建议或者问题欢迎提出
