### ISSUE TITLE
Got warning: missing space before text for line 25 of jade file ...

### ISSUE THREAD

**Issue by justbilt** [icylogic/carbon#20]
```
Warning: missing space before text for line 25 of jade file "/.../blog/themes/carbon/layout/_partial/footer.jade"
```

i get that warning when i generate in every post !

so i remove this code in `footer.jade`:

```
if theme.swiftype
  div#search
    a(href='javascript:void(0)')
      span#search-icon
        &#128269;
    input#search-input.hidden(name="search" placeholder="search" value="" tabindex="1" autocomplete="off" type="text")
```

that's  seem's resolved ! but that not is a good way, so i think i should tell you !

**Comment by icylogic** [comment]
Thanks for reporting. I've just fixed that:

Just merge these lines:

```
span#search-icon
  &#128269;
```

to 
`span#search-icon  &#128269;`

**Comment by justbilt** [comment]
wow, fixed so fast.  I think carbon is one of most minimalism theme for hexo, I really like it, thank you !
