### ISSUE TITLE
fancybox does not work

### ISSUE THREAD

**Issue by huangxjian** [icylogic/carbon#22]
Hi,fancybox does not work in this theme,but it worked when I changed another theme.Can you fix this problem , I love this clean and simple theme very much.

**Comment by icylogic** [comment]
Thanks. It works properly in my local tests. Could you provide details and/or your website?

**Comment by baibig** [comment]
It works after I add the attached file to the  scripts folder.I don't have the experience on front-end development,I add the file by finding the differences between your theme and the other themes.

**Comment by huangxjian** [comment]
Sorry,forgot to tell you .It works properly after I add the following script to the scripts folder.

``` javascript
var rUrl = /((([A-Za-z]{3,9}:(?:\/\/)?)(?:[-;:&=\+\$,\w]+@)?[A-Za-z0-9.-]+|(?:www.|[-;:&=\+\$,\w]+@)[A-Za-z0-9.-]+)((?:\/[\+~%\/.\w-_]*)?\??(?:[-\+=&;%@.\w_]*)#?(?:[.\!\/\\w]*))?)/;

/**
* Fancybox tag
*
* Syntax:
*   {% fancybox /path/to/image [/path/to/thumbnail] [title] %}
*/

hexo.extend.tag.register('gallery-img', function(args){
  var original = args.shift(),
    thumbnail = '';

  if (args.length && rUrl.test(args[0])){
    thumbnail = args.shift();
  }

  var title = args.join(' ');

  return '<a class="gallery-img" href="' + original + '" title="' + title + '">' +
    '<img src="' + ( original) + '" alt="' + title + '">'
    '</a>' +
    (title ? '<span class="caption">' + title + '</span>' : '');
});
```
