### ISSUE TITLE
adjust styles for lists & quotes

### ISSUE THREAD

**Issue by icylogic** [icylogic/carbon#7]

**Comment by thinkingofmaud** [comment]
Im rewriting the stylesheet. I'm not keeping the exact same proportions, but the overall look and feel should be similar. I already fixed the quotes.
That should also make the theme easier to customize (colors and fonts are all in _var for now). Expect a pull request in a few days.

**Comment by nathanwhy** [comment]
I like this theme, but I know little about css. How could I adjust style of `text`, which inside the ``.
